root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - google
  - plugin:import/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/typescript
  - plugin:vue/recommended
  - plugin:prettier-vue/recommended
  - prettier
  # - plugin:yaml/recommended
  - plugin:vuetify/base
  - '@vue/eslint-config-prettier'
  - plugin:vuejs-accessibility/recommended
plugins:
  - vue
  - vuetify
  # - yaml
  - eslint-plugin-tsdoc
  - '@typescript-eslint'
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
  createDefaultProgram: true
  project: ./tsconfig.json
rules:
  new-cap: off
  no-invalid-this: off
  no-unused-vars: warn
  require-jsdoc: warn
  tsdoc/syntax: warn
  valid-jsdoc: off
  vue/html-self-closing: [error, html: { void: always }]
  vue/multi-word-component-names: warn
settings:
  import/resolver:
    typescript: {}
    alias:
      map:
        - ['@', './src']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
        - .vue
