// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleBlock: typeof import('./src/components/ArticleBlock.vue')['default']
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    FigureBlock: typeof import('./src/components/FigureBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopArticleBlock: typeof import('./src/components/TopArticleBlock.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAutocomplete: typeof import('vuetify/lib')['VAutocomplete']
    VBreadcrumbs: typeof import('vuetify/lib')['VBreadcrumbs']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VHover: typeof import('vuetify/lib')['VHover']
    VIcon: typeof import('vuetify/lib')['VIcon']
    ViewCount: typeof import('./src/components/ViewCount.vue')['default']
    VImg: typeof import('vuetify/lib')['VImg']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemGroup: typeof import('vuetify/lib')['VListItemGroup']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VRow: typeof import('vuetify/lib')['VRow']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VSubheader: typeof import('vuetify/lib')['VSubheader']
    VSwitch: typeof import('vuetify/lib')['VSwitch']
  }

}
