// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleBlock: typeof import('./src/components/ArticleBlock.vue')['default']
    FigureBlock: typeof import('./src/components/FigureBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopArticleBlock: typeof import('./src/components/TopArticleBlock.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VBreadcrumbs: typeof import('vuetify/lib')['VBreadcrumbs']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VMain: typeof import('vuetify/lib')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VResponsive: typeof import('vuetify/lib')['VResponsive']
    VRow: typeof import('vuetify/lib')['VRow']
    VSheet: typeof import('vuetify/lib')['VSheet']
    VSkeletonLoader: typeof import('vuetify/lib')['VSkeletonLoader']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
  }
}

export {}
